/* -*- coding: utf-8-unix -*- */

#include "IntParser.h"
#include <stdlib.h>

/* function body of a parser to be generated by mult(a) */
static int mult_func(void* arg, Source src, Ctx* ex) {
  int a = (int)(intptr_t)arg;
  return a * atoi(parse(many1(digit), src, ex));
}

/* a parser generator 'mult(a)' */
PARSER(Int) mult(int a) {
  /* construct an instance of PARSER(Int) */
  return PARSER_GEN(Int)(mult_func, (void*)(intptr_t)a);
}
