/* -*- coding:utf-8-unix -*- */

#include <cparsec2.h>

FOREACH(DEFINE_EXPECTS, TYPESET(1));

FOREACH(DEFINE_MANY, TYPESET(0));
FOREACH(DEFINE_MANY1, TYPESET(0));

FOREACH(DEFINE_CONS, TYPESET(0));
FOREACH(DEFINE_SEQ, TYPESET(0));

FOREACH(DEFINE_SKIP, TYPESET(1));
FOREACH(DEFINE_SKIP1ST, TYPESET(1));
FOREACH(DEFINE_SKIP2ND, TYPESET(1));

FOREACH(DEFINE_EITHER, TYPESET(1));

FOREACH(DEFINE_TRYP, TYPESET(1));

FOREACH(DEFINE_TOKEN, TYPESET(1));
